In [51]:
f = open("D:/testLab/wordList.txt", "r")
l = []
m = []

import numpy as np

for i in f.readlines():
    l.append((str(i).lower())[:-1])
    m.append(len(i)-1)

f.close()

m = max(m)
t = []
X = []
for i in l:
    for k in ("0"*(m-len(i))):
        t.append(k)
    for j in i:
        t.append(str(ord(j)-96))
    X.append(t)
    t = []

y = []
X_new = []
d = {}
for i in range(len(X)):
    d = {}
    for j in X[i]:
        if (j != '0'):
            if j in d:
                d[j] += 1
            else:
                d[j] = 1
    d2 = {}
    for j in range(len(d)):
        el = ""
        elM = -1
        for k in d:
            if d[k] > elM and k not in d2:
                elM = d[k]
                el = k
        d2[el] = elM
    d = d2
    for j in d:
        newX = [0 for k in range(len(X[i]))]
        for k in d:
            if j == k:
                break
            else:
                for I in range(len(X[i])):
                    if X[i][I] == k:
                        newX[I] = k
        y.append(j)
        newX.insert(0, len(l[i]))
        X_new.append(newX)

X = []
for i in X_new:
    X.append(list(map(int, i)))
y = list(map(int, y))
X = np.array(X)
y = np.array(y)
y.reshape((-1, 1))

array([[ 1],
       [ 1],
       [ 1],
       ...,
       [ 1],
       [26],
       [26]])

In [52]:
print(X[0])
print(X[1])
print(X[2])
print(X[3])
print(X[4])

[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0]
[6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [64]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [66]:
y_train = tf.keras.utils.to_categorical(y_train - 1, num_classes=26)
y_test = tf.keras.utils.to_categorical(y_test - 1, num_classes=26)

In [67]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann.add(tf.keras.layers.Dense(units=128, activation='relu'))
ann.add(tf.keras.layers.Dense(units=26, activation='softmax'))
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [68]:
ann.fit(X_train, y_train, batch_size = 64, epochs = 50) # 32

Epoch 1/50
21016/21016 [==============================] - 142s 7ms/step - loss: 2.8033 - accuracy: 0.1539
Epoch 2/50
21016/21016 [==============================] - 153s 7ms/step - loss: 2.6905 - accuracy: 0.1879
Epoch 3/50
21016/21016 [==============================] - 156s 7ms/step - loss: 2.6408 - accuracy: 0.2002
Epoch 4/50
21016/21016 [==============================] - 137s 7ms/step - loss: 2.6109 - accuracy: 0.2074
Epoch 5/50
21016/21016 [==============================] - 142s 7ms/step - loss: 2.5888 - accuracy: 0.2132
Epoch 6/50
 9773/21016 [============>.................] - ETA: 1:22 - loss: 2.5742 - accuracy: 0.2174

KeyboardInterrupt: 

In [69]:
an = tf.keras.models.Sequential()
an.add(tf.keras.layers.Dense(units=128, activation='relu')) 
an.add(tf.keras.layers.Dense(units=64, activation='relu')) 
an.add(tf.keras.layers.Dense(units=64, activation='relu')) 
an.add(tf.keras.layers.Dense(units=32, activation='relu'))
an.add(tf.keras.layers.Dense(units=26, activation='softmax'))
an.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [70]:
an.fit(X_train, y_train, batch_size = 64, epochs = 50) # 32

Epoch 1/50
15484/21016 [=====================>........] - ETA: 25s - loss: 2.8531 - accuracy: 0.1400

KeyboardInterrupt: 

In [28]:
ann2 = tf.keras.models.Sequential()
ann2.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann2.add(tf.keras.layers.Dense(units=64, activation='relu')) 
ann2.add(tf.keras.layers.Dense(units=64, activation='relu')) 
ann2.add(tf.keras.layers.Dense(units=64, activation='relu')) 
ann2.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann2.add(tf.keras.layers.Dense(units=26, activation='softmax'))
ann2.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [29]:
ann2.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
42031/42031 [==============================] - 68s 2ms/step - loss: 2.8318 - accuracy: 0.1470
Epoch 2/50
42031/42031 [==============================] - 61s 1ms/step - loss: 2.7379 - accuracy: 0.1749
Epoch 3/50
42031/42031 [==============================] - 60s 1ms/step - loss: 2.7018 - accuracy: 0.1832
Epoch 4/50
42031/42031 [==============================] - 60s 1ms/step - loss: 2.6821 - accuracy: 0.1883
Epoch 5/50
42031/42031 [==============================] - 59s 1ms/step - loss: 2.6685 - accuracy: 0.1916
Epoch 6/50
42031/42031 [==============================] - 63s 1ms/step - loss: 2.6584 - accuracy: 0.1941
Epoch 7/50
42031/42031 [==============================] - 65s 2ms/step - loss: 2.6516 - accuracy: 0.1961
Epoch 8/50
14355/42031 [=========>....................] - ETA: 47s - loss: 2.6455 - accuracy: 0.1971

KeyboardInterrupt: 

In [30]:
ann3 = tf.keras.models.Sequential()
ann3.add(tf.keras.layers.Dense(units=32, activation='relu'))
ann3.add(tf.keras.layers.Dense(units=32, activation='relu')) 
ann3.add(tf.keras.layers.Dense(units=32, activation='relu')) 
ann3.add(tf.keras.layers.Dense(units=32, activation='relu')) 
ann3.add(tf.keras.layers.Dense(units=32, activation='relu')) 
ann3.add(tf.keras.layers.Dense(units=32, activation='relu')) 
ann3.add(tf.keras.layers.Dense(units=32, activation='relu'))
ann3.add(tf.keras.layers.Dense(units=26, activation='softmax'))
ann3.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [31]:
ann3.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
42031/42031 [==============================] - 68s 2ms/step - loss: 2.8607 - accuracy: 0.1369
Epoch 2/50
38175/42031 [==========================>...] - ETA: 6s - loss: 2.7892 - accuracy: 0.1601

KeyboardInterrupt: 

In [32]:
ann4 = tf.keras.models.Sequential()
ann4.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann4.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann4.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann4.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann4.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann4.add(tf.keras.layers.Dense(units=128, activation='relu'))
ann4.add(tf.keras.layers.Dense(units=26, activation='softmax'))
ann4.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [33]:
ann4.fit(X_train, y_train, batch_size = 64, epochs = 50)

Epoch 1/50
21016/21016 [==============================] - 48s 2ms/step - loss: 2.8158 - accuracy: 0.1520
Epoch 2/50
 1461/21016 [=>............................] - ETA: 41s - loss: 2.7339 - accuracy: 0.1764

KeyboardInterrupt: 

In [34]:
ann5 = tf.keras.models.Sequential()
ann5.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann5.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann5.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann5.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann5.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann5.add(tf.keras.layers.Dense(units=128, activation='relu'))
ann5.add(tf.keras.layers.Dense(units=26, activation='softmax'))
ann5.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [35]:
ann5.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
42031/42031 [==============================] - 80s 2ms/step - loss: 2.8094 - accuracy: 0.1527
Epoch 2/50
42031/42031 [==============================] - 81s 2ms/step - loss: 2.7104 - accuracy: 0.1812
Epoch 3/50
42031/42031 [==============================] - 79s 2ms/step - loss: 2.6762 - accuracy: 0.1898
Epoch 4/50
42031/42031 [==============================] - 82s 2ms/step - loss: 2.6568 - accuracy: 0.1947
Epoch 5/50
29057/42031 [===================>..........] - ETA: 26s - loss: 2.6470 - accuracy: 0.1973

KeyboardInterrupt: 

In [36]:
ann6 = tf.keras.models.Sequential()
ann6.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann6.add(tf.keras.layers.Dense(units=128, activation='relu')) 
ann6.add(tf.keras.layers.Dense(units=128, activation='relu'))
ann6.add(tf.keras.layers.Dense(units=26, activation='softmax'))
ann6.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [38]:
ann6.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
42031/42031 [==============================] - 66s 2ms/step - loss: 2.8149 - accuracy: 0.1531
Epoch 2/50
42031/42031 [==============================] - 58s 1ms/step - loss: 2.7107 - accuracy: 0.1842
Epoch 3/50
42031/42031 [==============================] - 55s 1ms/step - loss: 2.6718 - accuracy: 0.1937
Epoch 4/50
42031/42031 [==============================] - 55s 1ms/step - loss: 2.6496 - accuracy: 0.1988
Epoch 5/50
42031/42031 [==============================] - 55s 1ms/step - loss: 2.6354 - accuracy: 0.2024
Epoch 6/50
42031/42031 [==============================] - 55s 1ms/step - loss: 2.6254 - accuracy: 0.2060
Epoch 7/50
42031/42031 [==============================] - 55s 1ms/step - loss: 2.6173 - accuracy: 0.2079
Epoch 8/50
42031/42031 [==============================] - 55s 1ms/step - loss: 2.6108 - accuracy: 0.2096
Epoch 9/50
42031/42031 [==============================] - 56s 1ms/step - loss: 2.6047 - accuracy: 0.2113
Epoch 10/50
42031/42031 [==============================

KeyboardInterrupt: 

In [39]:
ann7 = tf.keras.models.Sequential()
ann7.add(tf.keras.layers.Dense(units=256, activation='relu')) 
ann7.add(tf.keras.layers.Dense(units=256, activation='relu')) 
ann7.add(tf.keras.layers.Dense(units=256, activation='relu')) 
ann7.add(tf.keras.layers.Dense(units=256, activation='relu'))
ann7.add(tf.keras.layers.Dense(units=26, activation='softmax'))
ann7.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [40]:
ann7.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
42031/42031 [==============================] - 96s 2ms/step - loss: 2.7886 - accuracy: 0.1599
Epoch 2/50
42031/42031 [==============================] - 99s 2ms/step - loss: 2.6769 - accuracy: 0.1914
Epoch 3/50
42031/42031 [==============================] - 101s 2ms/step - loss: 2.6399 - accuracy: 0.2011
Epoch 4/50
42031/42031 [==============================] - 96s 2ms/step - loss: 2.6171 - accuracy: 0.2073
Epoch 5/50
42031/42031 [==============================] - 94s 2ms/step - loss: 2.6041 - accuracy: 0.2109
Epoch 6/50
42031/42031 [==============================] - 94s 2ms/step - loss: 2.5952 - accuracy: 0.2132
Epoch 7/50
42031/42031 [==============================] - 94s 2ms/step - loss: 2.5897 - accuracy: 0.2155
Epoch 8/50
42031/42031 [==============================] - 96s 2ms/step - loss: 2.6279 - accuracy: 0.2160
Epoch 9/50
42031/42031 [==============================] - 97s 2ms/step - loss: 2.6043 - accuracy: 0.2177
Epoch 10/50
42031/42031 [=============================

KeyboardInterrupt: 